import type { PlotRow } from "@/lib/types";

const now = "2026-09-26T00:00:00.000Z";

export const DEMO_PLOTS: PlotRow[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    farmer_name: "Farmer A",
    farmer_id: "F-1001",
    village_id: "V-01",
    village_name: "Village A",
    base: "Base A",
    field_type: "Owner plot",
    plot_id: "1",
    lat: 24.1278,
    long: 78.9877,
    sample_id: "22ERPO",
    sample_date: "2026-09-20",
    sample_picture_url: null,
    core_cut_type: "Histosols",
    sample_lat: 24.1278,
    sample_long: 78.9877,
    surveyor_name: "Demo Surveyor",
    surveyor_email: "demo@maticarbon.com",
    status: "enrolled",
    collected_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    farmer_name: "Farmer A",
    farmer_id: "F-1001",
    village_id: "V-01",
    village_name: "Village A",
    base: "Base A",
    field_type: "Displayed plot",
    plot_id: "2",
    lat: 24.1291,
    long: 78.9894,
    sample_id: null,
    sample_date: null,
    sample_picture_url: null,
    core_cut_type: null,
    sample_lat: null,
    sample_long: null,
    surveyor_name: null,
    surveyor_email: null,
    status: "pending",
    collected_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    farmer_name: "Farmer B",
    farmer_id: "F-1002",
    village_id: "V-01",
    village_name: "Village A",
    base: "Base A",
    field_type: "Owner plot",
    plot_id: "1",
    lat: 24.1312,
    long: 78.9841,
    sample_id: null,
    sample_date: null,
    sample_picture_url: null,
    core_cut_type: null,
    sample_lat: null,
    sample_long: null,
    surveyor_name: null,
    surveyor_email: null,
    status: "pending",
    collected_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "44444444-4444-4444-8444-444444444444",
    farmer_name: "Farmer C",
    farmer_id: "F-1003",
    village_id: "V-01",
    village_name: "Village A",
    base: "Base A",
    field_type: "Owner plot",
    plot_id: "1",
    lat: 24.1254,
    long: 78.9912,
    sample_id: null,
    sample_date: null,
    sample_picture_url: null,
    core_cut_type: null,
    sample_lat: null,
    sample_long: null,
    surveyor_name: null,
    surveyor_email: null,
    status: "pending",
    collected_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "55555555-5555-4555-8555-555555555555",
    farmer_name: "Farmer D",
    farmer_id: "F-2001",
    village_id: "V-02",
    village_name: "Village B",
    base: "Base A",
    field_type: "Owner plot",
    plot_id: "1",
    lat: 24.1402,
    long: 79.0011,
    sample_id: null,
    sample_date: null,
    sample_picture_url: null,
    core_cut_type: null,
    sample_lat: null,
    sample_long: null,
    surveyor_name: null,
    surveyor_email: null,
    status: "pending",
    collected_at: null,
    created_at: now,
    updated_at: now,
  },
];
